# Generated by Django 5.1.1 on 2024-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project title')),
                ('desc', models.CharField(max_length=500, verbose_name='Project description')),
                ('github', models.CharField(max_length=100, verbose_name='Github repo')),
                ('href', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link to live demo (if any)')),
                ('img', models.ImageField(upload_to='static/images/projects', verbose_name='Image')),
            ],
        ),
    ]
