# Generated by Django 5.1.1 on 2024-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='media/images/projects/', verbose_name='Image'),
        ),
    ]
