# Generated by Django 5.1.1 on 2024-09-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('icon', models.ImageField(upload_to='media/images/techs/', verbose_name='Icon')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='techStack',
            field=models.ManyToManyField(to='projects.technology'),
        ),
    ]
