# Generated by Django 5.1.1 on 2024-09-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_technology_project_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/techs/', verbose_name='Icon'),
        ),
    ]
