# Generated by Django 5.1.1 on 2024-09-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_technology_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='techStack',
            field=models.ManyToManyField(related_name='projects', to='projects.technology'),
        ),
    ]
