# Generated by Django 5.1.1 on 2024-09-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='techStack',
            field=models.ManyToManyField(to='projects.technology'),
        ),
    ]
